{
  users (
    where: {
      id: "0x1908bb246da7d358e4f79cea8b3d2ce5e81e6d64"
    }
  ) {
    reserves{
      id,
      reserve{
        symbol,
        usageAsCollateralEnabled,
        decimals
      },
      currentATokenBalance,
      currentVariableDebt,
      currentStableDebt
    }
  }
}