{
  userReserves(
    where:{
      id: "0x1908bb246da7d358e4f79cea8b3d2ce5e81e6d640xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc20xb53c1a33016b2dc2ff3653530bff1848a515c8c5"
    }
  ){
    id,
    reserve{
          symbol,
          decimals
    },
    aTokenBalanceHistory{
      timestamp,
      scaledATokenBalance
    },
    depositHistory{
      timestamp,
      amount
    },
    redeemUnderlyingHistory{
      timestamp,
      amount
    },
    liquidationCallHistory{
      timestamp,
      collateralAmount
    }
  }
}
