{
  deposits(
    where: {
   	  id_in : $aave_ids
    } 
  ) {
    id, timestamp,
    reserve{
      symbol, decimals
    },
    amount
  },
  usageAsCollaterals(
    where: {
      id_in : $aave_ids
    }
  ) {
    id, timestamp,
    reserve{
      symbol
    },
    toState
  },
  redeemUnderlyings(
    where: {
      id_in : $aave_ids
    }
  ) {
    id, timestamp, 
    reserve {
      symbol,  decimals
    },
    amount
  },
  borrows (
  where: {
      id_in : $aave_ids
    }
  ) {
    id, timestamp, 
    reserve {
      symbol, decimals
    },
    amount
  },
  repays (
  where: {
      id_in : $aave_ids
    }
  ) {
    id, timestamp, 
    reserve {
      symbol, decimals
    },
    amount
  },
  swaps (
    where: {
      id_in : $aave_ids
    }
  ) {
    id, timestamp, 
    reserve {
      symbol
    },
    borrowRateModeTo
  },
  liquidationCalls (
    where: {
      id_in : $aave_ids
    }
  ) {
    id, timestamp,
    collateralReserve {
      symbol, decimals
    },
    principalReserve {
      symbol, decimals
    },
    collateralAmount,
    principalAmount,
    liquidator
  },
  flashLoans (
    where: {
      initiator : "0x364f7fd945b8c76c3c77d6ac253f1fea3b65e00d"
    }
  ) {
    id, timestamp,
    reserve {
      symbol, decimals
    },
    amount
  }
}
